trigger:
  branches:
    include: [dev,test,prod]
    

parameters:
- name: items_in_scope
  displayName: Enter Fabric items to be deployed
  type: string
  default: '["Notebook","DataPipeline","Lakehouse","SemanticModel","Report"]'


variables:
  - name: target_env
    value: ${{ replace(variables['Build.SourceBranch'], 'refs/heads/', '') }}
  # This variable group contains the workspace names based on naming convention "[branch]WorkspaceName". It also contains the gitFolder to be referenced in the python script.
  - group: Fabric_Deployment_Group_NS
stages:
  - stage: DeployToFabric
    displayName: "Deploy to Fabric Workspace"
    jobs:
      - job: Deployment
        displayName: "Deploy Resources"
        pool:
          name: Azure Pipelines
        steps:
          # Use Python Version 3.12
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.12'
              addToPath: true
            displayName: "Set up Python Environment"
          # Install Dependencies
          - script: |
              python -m pip install --upgrade pip
              pip install fabric-cicd 
            displayName: "Install Fabric CICD Library"
          # Get Fabric/Power BI API token using Azure CLI
          - task: AzureCLI@2
            displayName: 'Get Fabric Access Token'
            inputs:
              azureSubscription: 'ME-MngEnvMCAP705223-milofarrell-1 (e9d6252f-db1f-4a66-93ab-c54eab93df93)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                TOKEN=$(az account get-access-token --resource=https://analysis.windows.net/powerbi/api --query accessToken -o tsv)
          # Run deployment using fabric-cicd
          - task: PythonScript@0
            inputs:
              scriptSource: 'filePath'
              scriptPath: 'scripts/deploy/deploy-to-fabric.py'
              arguments: '--items_in_scope ${{ parameters.items_in_scope }} --target_env $(target_env)'
            env:
              FABRIC_TOKEN: $(FABRIC_TOKEN)
            displayName: 'Run deployment using fabric-cicd'
